= CalConnect Standard: Calendar and scheduling -- iCalendar Transport-Independent Interoperability Protocol (iTIP)

This work item belongs to CalConnect TC CALENDAR.

image:https://github.com/CalConnect/cc-iTip-rewrite/workflows/generate/badge.svg["Build Status", link="https://github.com/CalConnect/cc-iTip-rewrite/actions?workflow=generate"]

This document is available in its rendered forms here:

* https://calconnect.github.io/cc-iTip-rewrite/[Calendar and scheduling -- iCalendar Transport-Independent Interoperability Protocol (iTIP)]

== General

This document specifies the Calendar and scheduling -- iCalendar
Transport-Independent Interoperability Protocol (iTIP).

The document is published as the following:

* CalConnect CC 51008
// * ISO (DOCNUMBER)
* IETF draft-ietf-calext-itipbis


== Fetching the document

Click on "Code > Local" to clone this repository.


== Installing build tools

See https://www.metanorma.com/author/topics/install/


== Running via Docker or locally

If you have installed the build tools locally, and wish to run the
locally-installed compilation tools, there is nothing further to set.

If you don't want to deal with local dependencies, use the docker:

[source,sh]
----
docker run -v "$(pwd)":/metanorma -w /metanorma -it metanorma/mn metanorma site generate --agree-to-terms
----


== Building the document

[source,sh]
----
metanorma site generate --agree-to-terms
----

The generated documents are accessible under `_site/`.


== Iterating the document

[source,sh]
----
metanorma site generate --agree-to-terms
open _site/index.html
----


== IETF: Checking against idnits

https://tools.ietf.org/tools/idnits/[idnits] is the RFC checking tool prior to
submissions.

[source,sh]
----
idnits draft-ietf-calext-itipbis.nits
----


== License

Copyright its respective authors and CalConnect.
